### ISSUE TITLE
Fresh installation (atom and cflint)

### ISSUE THREAD

**Issue by maquejp** [ditinc/linter-cflint#22]
Hello,
I just installed Atom and try to make it work with linter-cfLint without success. I have the error "An unexpected error occured with linter-cflint. See the debug log for details."
I have set the java path to "C:\PROGRA~1\Java\JRE18~1.0_1\bin" ("C:\Program Files\Java\jre1.8.0_121") to be sure. Note that this is the 64b.
A quick question, how do I access the log so I can provide more information?

**Comment by sjmatta** [comment]
View -> Developer -> Toggle Developer Tools should bring up the console. Please provide me with any relevant console logs you find. Thank you!

**Comment by bubbles8** [comment]
I am having the same issue. My system variable was already set.  I've also tried setting in the configuration settings.  I've had it disabled for couple months hoping there would be a fix soon ... here is what I get

Error: not found: javac.exe
    at F (.....\atom\packages\linter-cflint\node_modules\which\which.js:40:28)
    at E (.....\.atom\packages\linter-cflint\node_modules\which\which.js:43:29)
    at .....\.atom\packages\linter-cflint\node_modules\which\which.js:54:16
    at FSReqWrap.oncomplete (fs.js:123:15)
        (anonymous function) @ main.js:127
        step @ .....\.atom\packages\linter-cflint\lib\main.js:7
        _tickCallback @ internal/process/next_tick.js:103
